// Styles
import '../sass/app.scss'

// Audio
import '../audio/animals/sounds-160.mp3'
import '../audio/animals/sounds-160.ogg'

// Animals images
// import 'imagesPath/animals/bear.svg'
// import 'imagesPath/animals/bird.svg'
// import 'imagesPath/animals/camel.svg'
// import 'imagesPath/animals/cat.svg'
// import 'imagesPath/animals/chicken.svg'
// import 'imagesPath/animals/cow.svg'
// import 'imagesPath/animals/dog.svg'
// import 'imagesPath/animals/dolphin.svg'
// import 'imagesPath/animals/dove.svg'
// import 'imagesPath/animals/duck.svg'
// import 'imagesPath/animals/elephant.svg'
// import 'imagesPath/animals/frog.svg'
// import 'imagesPath/animals/goat.svg'
// import 'imagesPath/animals/goose.svg'
// import 'imagesPath/animals/hamster.svg'
// import 'imagesPath/animals/horse.svg'
// import 'imagesPath/animals/lion.svg'
// import 'imagesPath/animals/macaw.svg'
// import 'imagesPath/animals/monkey.svg'
// import 'imagesPath/animals/mouse.svg'
// import 'imagesPath/animals/owl.svg'
// import 'imagesPath/animals/pig.svg'
// import 'imagesPath/animals/rooster.svg'
// import 'imagesPath/animals/sheep.svg'
// import 'imagesPath/animals/snake.svg'
